[package]
name = "clarramore/-g"
version = "0.1.35"
registry = "https://github.com/UpliftGames/wally-index"
description="An old multi-purpose function library."
authors = ["VisualPlugin <Github : @Windows81>"]
realm = "shared"
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]
exclude = ["aftman.toml"]
[dependencies]
